import { Framework } from '../types/index.ts';

export const AI_OPS_FRAMEWORKS: Framework[] = [
    { id: 'ragas', acronym: 'RAGAS', name: 'RAG Assessment', description: 'Faithfulness, Answer Relevance, Context Precision.', category: 'Operaciones de IA', source: { name: 'Exploding Gradients', url: 'https://github.com/explodinggradients/ragas' } },
    { id: 'tru-lens', acronym: 'TruLens', name: 'TruLens Eval', description: 'Feedback functions for LLM apps.', category: 'Operaciones de IA', source: { name: 'TruEra', url: 'https://www.trulens.org/' } },
    { id: 'arize-phoenix-aiops', acronym: 'Phoenix', name: 'Arize Phoenix', description: 'LLM observability and eval.', category: 'Operaciones de IA', source: { name: 'Arize AI', url: 'https://phoenix.arize.com/' } },
    { id: 'langsmith-aiops', acronym: 'LangSmith', name: 'LangSmith', description: 'Debug, test, eval, and monitor LLM apps.', category: 'Operaciones de IA', source: { name: 'LangChain', url: 'https://smith.langchain.com/' } },
    { id: 'weights-biases', acronym: 'W&B', name: 'Weights & Biases', description: 'ML experiment tracking.', category: 'Operaciones de IA', source: { name: 'W&B', url: 'https://wandb.ai/' } },
    { id: 'mlflow', acronym: 'MLflow', name: 'MLflow', description: 'Lifecycle management.', category: 'Operaciones de IA', source: { name: 'Databricks', url: 'https://mlflow.org/' } },
    { id: 'kubeflow', acronym: 'Kubeflow', name: 'Kubeflow', description: 'ML on Kubernetes.', category: 'Operaciones de IA', source: { name: 'Google', url: 'https://www.kubeflow.org/' } },
    { id: 'seldon', acronym: 'Seldon', name: 'Seldon Core', description: 'Model serving.', category: 'Operaciones de IA', source: { name: 'Seldon', url: 'https://www.seldon.io/' } },
    { id: 'bentoml', acronym: 'BentoML', name: 'BentoML', description: 'Model serving framework.', category: 'Operaciones de IA', source: { name: 'BentoML', url: 'https://www.bentoml.com/' } },
    { id: 'ray-serve', acronym: 'Ray', name: 'Ray Serve', description: 'Scalable model serving.', category: 'Operaciones de IA', source: { name: 'Anyscale', url: 'https://docs.ray.io/en/latest/serve/index.html' } },
    { id: 'torch-serve', acronym: 'TorchServe', name: 'TorchServe', description: 'PyTorch model serving.', category: 'Operaciones de IA', source: { name: 'PyTorch', url: 'https://pytorch.org/serve/' } },
    { id: 'tf-serving', acronym: 'TFServing', name: 'TensorFlow Serving', description: 'TF model serving.', category: 'Operaciones de IA', source: { name: 'TensorFlow', url: 'https://www.tensorflow.org/tfx/guide/serving' } },
    { id: 'kserve', acronym: 'KServe', name: 'KServe', description: 'Serverless inference on K8s.', category: 'Operaciones de IA', source: { name: 'KServe', url: 'https://kserve.github.io/website/' } },
    { id: 'prometheus-grafana', acronym: 'Prom/Graf', name: 'Prometheus & Grafana', description: 'Metrics and visualization.', category: 'Operaciones de IA', source: { name: 'CNCF', url: 'https://prometheus.io/' } },
    { id: 'elk-stack', acronym: 'ELK', name: 'ELK Stack', description: 'Elasticsearch, Logstash, Kibana.', category: 'Operaciones de IA', source: { name: 'Elastic', url: 'https://www.elastic.co/what-is/elk-stack' } },
    { id: 'opentelemetry', acronym: 'OTel', name: 'OpenTelemetry', description: 'Observability standard.', category: 'Operaciones de IA', source: { name: 'CNCF', url: 'https://opentelemetry.io/' } },
    { id: 'great-expectations-aiops', acronym: 'GX', name: 'Great Expectations', description: 'Data validation.', category: 'Operaciones de IA', source: { name: 'GX', url: 'https://greatexpectations.io/' } },
    { id: 'dvc', acronym: 'DVC', name: 'Data Version Control', description: 'Git for data.', category: 'Operaciones de IA', source: { name: 'Iterative', url: 'https://dvc.org/' } },
    { id: 'pachyderm', acronym: 'Pachyderm', name: 'Pachyderm', description: 'Data lineage and pipelines.', category: 'Operaciones de IA', source: { name: 'HPE', url: 'https://www.pachyderm.com/' } },
    { id: 'airflow', acronym: 'Airflow', name: 'Apache Airflow', description: 'Workflow orchestration.', category: 'Operaciones de IA', source: { name: 'Apache', url: 'https://airflow.apache.org/' } },
    { id: 'prefect', acronym: 'Prefect', name: 'Prefect', description: 'Modern workflow orchestration.', category: 'Operaciones de IA', source: { name: 'Prefect', url: 'https://www.prefect.io/' } },
    { id: 'dagster', acronym: 'Dagster', name: 'Dagster', description: 'Data orchestrator.', category: 'Operaciones de IA', source: { name: 'Dagster', url: 'https://dagster.io/' } },
    { id: 'flyte', acronym: 'Flyte', name: 'Flyte', description: 'K8s-native workflows.', category: 'Operaciones de IA', source: { name: 'Union.ai', url: 'https://flyte.org/' } },
    { id: 'metaflow', acronym: 'Metaflow', name: 'Metaflow', description: 'Data science framework.', category: 'Operaciones de IA', source: { name: 'Netflix', url: 'https://metaflow.org/' } },
    { id: 'zenml', acronym: 'ZenML', name: 'ZenML', description: 'MLOps framework.', category: 'Operaciones de IA', source: { name: 'ZenML', url: 'https://zenml.io/' } },
    { id: 'clearml', acronym: 'ClearML', name: 'ClearML', description: 'MLOps platform.', category: 'Operaciones de IA', source: { name: 'Allegro AI', url: 'https://clear.ml/' } },
    { id: 'comet', acronym: 'Comet', name: 'Comet ML', description: 'Experiment tracking.', category: 'Operaciones de IA', source: { name: 'Comet', url: 'https://www.comet.com/' } },
    { id: 'neptune', acronym: 'Neptune', name: 'Neptune.ai', description: 'Metadata store.', category: 'Operaciones de IA', source: { name: 'Neptune', url: 'https://neptune.ai/' } },
    { id: 'gradio', acronym: 'Gradio', name: 'Gradio', description: 'UI for ML models.', category: 'Operaciones de IA', source: { name: 'Hugging Face', url: 'https://gradio.app/' } },
    { id: 'streamlit', acronym: 'Streamlit', name: 'Streamlit', description: 'Data apps.', category: 'Operaciones de IA', source: { name: 'Snowflake', url: 'https://streamlit.io/' } },
    { id: 'chainlit', acronym: 'Chainlit', name: 'Chainlit', description: 'Chat UI for LLMs.', category: 'Operaciones de IA', source: { name: 'Chainlit', url: 'https://docs.chainlit.io/' } },
    { id: 'vllm', acronym: 'vLLM', name: 'vLLM', description: 'High-throughput serving.', category: 'Operaciones de IA', source: { name: 'Berkeley', url: 'https://github.com/vllm-project/vllm' } },
    { id: 'tgi', acronym: 'TGI', name: 'Text Generation Inference', description: 'Hugging Face serving.', category: 'Operaciones de IA', source: { name: 'Hugging Face', url: 'https://github.com/huggingface/text-generation-inference' } },
    { id: 'ctranslate2', acronym: 'CT2', name: 'CTranslate2', description: 'Fast inference engine.', category: 'Operaciones de IA', source: { name: 'OpenNMT', url: 'https://github.com/OpenNMT/CTranslate2' } },
    { id: 'ggml', acronym: 'GGML', name: 'GGML/GGUF', description: 'Tensor library for edge.', category: 'Operaciones de IA', source: { name: 'Georgi Gerganov', url: 'https://github.com/ggerganov/ggml' } },
    { id: 'llama-cpp', acronym: 'LlamaCpp', name: 'llama.cpp', description: 'Inference on CPU/Apple Silicon.', category: 'Operaciones de IA', source: { name: 'Georgi Gerganov', url: 'https://github.com/ggerganov/llama.cpp' } },
    { id: 'ollama', acronym: 'Ollama', name: 'Ollama', description: 'Local LLM runner.', category: 'Operaciones de IA', source: { name: 'Ollama', url: 'https://ollama.com/' } },
    { id: 'localai', acronym: 'LocalAI', name: 'LocalAI', description: 'OpenAI compatible API.', category: 'Operaciones de IA', source: { name: 'Mudler', url: 'https://localai.io/' } },
    { id: 'private-gpt-aiops', acronym: 'PrivateGPT', name: 'PrivateGPT', description: 'Offline RAG.', category: 'Operaciones de IA', source: { name: 'Zylon', url: 'https://github.com/zylon-ai/private-gpt' } },
    { id: 'h2o-gpt', acronym: 'h2oGPT', name: 'h2oGPT', description: 'Private LLM.', category: 'Operaciones de IA', source: { name: 'H2O.ai', url: 'https://github.com/h2oai/h2ogpt' } },
    { id: 'deep-eval', acronym: 'DeepEval', name: 'DeepEval', description: 'LLM evaluation framework.', category: 'Operaciones de IA', source: { name: 'Confident AI', url: 'https://github.com/confident-ai/deepeval' } },
    { id: 'prompt-foo', acronym: 'PromptFoo', name: 'Promptfoo', description: 'Test prompts.', category: 'Operaciones de IA', source: { name: 'Promptfoo', url: 'https://www.promptfoo.dev/' } },
    { id: 'giskard', acronym: 'Giskard', name: 'Giskard', description: 'AI quality assurance.', category: 'Operaciones de IA', source: { name: 'Giskard', url: 'https://www.giskard.ai/' } },
    { id: 'fiddler', acronym: 'Fiddler', name: 'Fiddler', description: 'Model monitoring.', category: 'Operaciones de IA', source: { name: 'Fiddler', url: 'https://www.fiddler.ai/' } },
    { id: 'whylabs', acronym: 'WhyLabs', name: 'WhyLabs', description: 'Data observability.', category: 'Operaciones de IA', source: { name: 'WhyLabs', url: 'https://whylabs.ai/' } },
    { id: 'evidently', acronym: 'Evidently', name: 'Evidently AI', description: 'ML monitoring.', category: 'Operaciones de IA', source: { name: 'Evidently', url: 'https://www.evidentlyai.com/' } },
    { id: 'uptrain', acronym: 'UpTrain', name: 'UpTrain', description: 'LLM evaluation.', category: 'Operaciones de IA', source: { name: 'UpTrain', url: 'https://uptrain.ai/' } },
    { id: 'honeyhive', acronym: 'HoneyHive', name: 'HoneyHive', description: 'Prompt management.', category: 'Operaciones de IA', source: { name: 'HoneyHive', url: 'https://honeyhive.ai/' } },
    { id: 'human-loop', acronym: 'HumanLoop', name: 'HumanLoop', description: 'LLM dev platform.', category: 'Operaciones de IA', source: { name: 'HumanLoop', url: 'https://humanloop.com/' } },
    { id: 'pezzo', acronym: 'Pezzo', name: 'Pezzo', description: 'Open source LLM platform.', category: 'Operaciones de IA', source: { name: 'Pezzo', url: 'https://github.com/pezzolabs/pezzo' } },
    { id: 'agentops', acronym: 'AgentOps', name: 'AgentOps', description: 'Observability for AI agents.', category: 'Operaciones de IA', source: { name: 'AgentOps', url: 'https://agentops.ai/' } },
    { id: 'helicone', acronym: 'Helicone', name: 'Helicone', description: 'Open source LLM observability.', category: 'Operaciones de IA', source: { name: 'Helicone', url: 'https://helicone.ai/' } },
    { id: 'portkey', acronym: 'Portkey', name: 'Portkey', description: 'LLM gateway and observability.', category: 'Operaciones de IA', source: { name: 'Portkey', url: 'https://portkey.ai/' } },
    { id: 'litellm', acronym: 'LiteLLM', name: 'LiteLLM', description: 'Call all LLM APIs using OpenAI format.', category: 'Operaciones de IA', source: { name: 'LiteLLM', url: 'https://github.com/BerriAI/litellm' } },
    { id: 'openllm', acronym: 'OpenLLM', name: 'OpenLLM', description: 'Run LLMs in production.', category: 'Operaciones de IA', source: { name: 'BentoML', url: 'https://github.com/bentoml/OpenLLM' } },
    { id: 'fastchat', acronym: 'FastChat', name: 'FastChat', description: 'Training and serving LLMs.', category: 'Operaciones de IA', source: { name: 'LMSYS', url: 'https://github.com/lm-sys/FastChat' } },
    { id: 'skypilot', acronym: 'SkyPilot', name: 'SkyPilot', description: 'Run LLMs on any cloud.', category: 'Operaciones de IA', source: { name: 'Berkeley', url: 'https://skypilot.co/' } },
    { id: 'run-ai', acronym: 'Run:ai', name: 'Run:ai', description: 'GPU orchestration platform.', category: 'Operaciones de IA', source: { name: 'Run:ai', url: 'https://www.run.ai/' } },
    { id: 'determined-ai', acronym: 'Determined', name: 'Determined AI', description: 'Deep learning training platform.', category: 'Operaciones de IA', source: { name: 'HPE', url: 'https://www.determined.ai/' } },
    { id: 'polyaxon', acronym: 'Polyaxon', name: 'Polyaxon', description: 'MLOps for Kubernetes.', category: 'Operaciones de IA', source: { name: 'Polyaxon', url: 'https://polyaxon.com/' } },
    { id: 'valohai', acronym: 'Valohai', name: 'Valohai', description: 'MLOps platform.', category: 'Operaciones de IA', source: { name: 'Valohai', url: 'https://valohai.com/' } },
    { id: 'iguazio', acronym: 'Iguazio', name: 'Iguazio', description: 'MLOps platform.', category: 'Operaciones de IA', source: { name: 'McKinsey', url: 'https://www.iguazio.com/' } },
    { id: 'domino-data', acronym: 'Domino', name: 'Domino Data Lab', description: 'Enterprise MLOps.', category: 'Operaciones de IA', source: { name: 'Domino', url: 'https://www.dominodatalab.com/' } },
    { id: 'paperspace', acronym: 'Paperspace', name: 'Paperspace', description: 'Cloud GPU computing.', category: 'Operaciones de IA', source: { name: 'DigitalOcean', url: 'https://www.paperspace.com/' } },
    { id: 'lambda-labs', acronym: 'Lambda', name: 'Lambda Labs', description: 'GPU cloud.', category: 'Operaciones de IA', source: { name: 'Lambda', url: 'https://lambdalabs.com/' } },
    { id: 'coreweave', acronym: 'CoreWeave', name: 'CoreWeave', description: 'Specialized cloud provider.', category: 'Operaciones de IA', source: { name: 'CoreWeave', url: 'https://www.coreweave.com/' } },
    { id: 'vast-ai', acronym: 'Vast', name: 'Vast.ai', description: 'GPU rental marketplace.', category: 'Operaciones de IA', source: { name: 'Vast.ai', url: 'https://vast.ai/' } },
    { id: 'runpod', acronym: 'RunPod', name: 'RunPod', description: 'GPU cloud.', category: 'Operaciones de IA', source: { name: 'RunPod', url: 'https://www.runpod.io/' } },
    { id: 'modal', acronym: 'Modal', name: 'Modal', description: 'Serverless GPU computing.', category: 'Operaciones de IA', source: { name: 'Modal', url: 'https://modal.com/' } },
    { id: 'banana-dev', acronym: 'Banana', name: 'Banana', description: 'Serverless GPU inference.', category: 'Operaciones de IA', source: { name: 'Banana', url: 'https://www.banana.dev/' } },
    { id: 'replicate', acronym: 'Replicate', name: 'Replicate', description: 'Run AI with an API.', category: 'Operaciones de IA', source: { name: 'Replicate', url: 'https://replicate.com/' } },
    { id: 'mystic', acronym: 'Mystic', name: 'Mystic', description: 'Pipeline AI platform.', category: 'Operaciones de IA', source: { name: 'Mystic', url: 'https://www.mystic.ai/' } },
    { id: 'fal-ai', acronym: 'Fal', name: 'Fal.ai', description: 'Generative media platform.', category: 'Operaciones de IA', source: { name: 'Fal', url: 'https://fal.ai/' } },
    { id: 'together-ai', acronym: 'Together', name: 'Together AI', description: 'Open source models API.', category: 'Operaciones de IA', source: { name: 'Together', url: 'https://www.together.ai/' } },
    { id: 'anyscale', acronym: 'Anyscale', name: 'Anyscale', description: 'Ray platform.', category: 'Operaciones de IA', source: { name: 'Anyscale', url: 'https://www.anyscale.com/' } },
    { id: 'fireworks-ai', acronym: 'Fireworks', name: 'Fireworks AI', description: 'Fast inference platform.', category: 'Operaciones de IA', source: { name: 'Fireworks', url: 'https://fireworks.ai/' } },
    { id: 'deepinfra', acronym: 'DeepInfra', name: 'DeepInfra', description: 'Inference API.', category: 'Operaciones de IA', source: { name: 'DeepInfra', url: 'https://deepinfra.com/' } },
    { id: 'perplexity-api', acronym: 'PPLX', name: 'Perplexity API', description: 'LLM API.', category: 'Operaciones de IA', source: { name: 'Perplexity', url: 'https://docs.perplexity.ai/' } },
    { id: 'groq', acronym: 'Groq', name: 'Groq', description: 'LPU inference engine.', category: 'Operaciones de IA', source: { name: 'Groq', url: 'https://groq.com/' } },
    { id: 'sambanova', acronym: 'SambaNova', name: 'SambaNova', description: 'AI hardware platform.', category: 'Operaciones de IA', source: { name: 'SambaNova', url: 'https://sambanova.ai/' } },
    { id: 'cerebras', acronym: 'Cerebras', name: 'Cerebras', description: 'Wafer-scale engine.', category: 'Operaciones de IA', source: { name: 'Cerebras', url: 'https://www.cerebras.net/' } },
    { id: 'graphcore', acronym: 'Graphcore', name: 'Graphcore', description: 'IPU hardware.', category: 'Operaciones de IA', source: { name: 'Graphcore', url: 'https://www.graphcore.ai/' } },
    { id: 'habana', acronym: 'Habana', name: 'Habana Gaudi', description: 'AI processors.', category: 'Operaciones de IA', source: { name: 'Intel', url: 'https://habana.ai/' } },
    { id: 'tenstorrent', acronym: 'Tenstorrent', name: 'Tenstorrent', description: 'RISC-V AI chips.', category: 'Operaciones de IA', source: { name: 'Tenstorrent', url: 'https://tenstorrent.com/' } },
    { id: 'modular', acronym: 'Modular', name: 'Modular', description: 'AI infrastructure.', category: 'Operaciones de IA', source: { name: 'Modular', url: 'https://www.modular.com/' } },
    { id: 'mojo', acronym: 'Mojo', name: 'Mojo', description: 'AI programming language.', category: 'Operaciones de IA', source: { name: 'Modular', url: 'https://www.modular.com/mojo' } },
    { id: 'triton', acronym: 'Triton', name: 'Triton Inference Server', description: 'NVIDIA serving.', category: 'Operaciones de IA', source: { name: 'NVIDIA', url: 'https://developer.nvidia.com/triton-inference-server' } },
    { id: 'tensorrt-llm', acronym: 'TRT-LLM', name: 'TensorRT-LLM', description: 'LLM optimization.', category: 'Operaciones de IA', source: { name: 'NVIDIA', url: 'https://github.com/NVIDIA/TensorRT-LLM' } },
    { id: 'onnx-runtime', acronym: 'ONNX', name: 'ONNX Runtime', description: 'Cross-platform inference.', category: 'Operaciones de IA', source: { name: 'Microsoft', url: 'https://onnxruntime.ai/' } },
    { id: 'openvino', acronym: 'OpenVINO', name: 'OpenVINO', description: 'Intel inference.', category: 'Operaciones de IA', source: { name: 'Intel', url: 'https://docs.openvino.ai/' } },
    { id: 'tvm', acronym: 'TVM', name: 'Apache TVM', description: 'ML compiler.', category: 'Operaciones de IA', source: { name: 'Apache', url: 'https://tvm.apache.org/' } },
    { id: 'mlir', acronym: 'MLIR', name: 'MLIR', description: 'Compiler infrastructure.', category: 'Operaciones de IA', source: { name: 'LLVM', url: 'https://mlir.llvm.org/' } },
    { id: 'jax', acronym: 'JAX', name: 'JAX', description: 'Autograd and XLA.', category: 'Operaciones de IA', source: { name: 'Google', url: 'https://github.com/google/jax' } },
    { id: 'flax', acronym: 'Flax', name: 'Flax', description: 'Neural networks for JAX.', category: 'Operaciones de IA', source: { name: 'Google', url: 'https://github.com/google/flax' } },
    { id: 'haiku', acronym: 'Haiku', name: 'Haiku', description: 'Neural networks for JAX.', category: 'Operaciones de IA', source: { name: 'DeepMind', url: 'https://github.com/google-deepmind/dm-haiku' } },
    { id: 'optax', acronym: 'Optax', name: 'Optax', description: 'Optimization for JAX.', category: 'Operaciones de IA', source: { name: 'DeepMind', url: 'https://github.com/google-deepmind/optax' } },
    { id: 'chex', acronym: 'Chex', name: 'Chex', description: 'Testing for JAX.', category: 'Operaciones de IA', source: { name: 'DeepMind', url: 'https://github.com/google-deepmind/chex' } },
    { id: 'distrax', acronym: 'Distrax', name: 'Distrax', description: 'Distributions for JAX.', category: 'Operaciones de IA', source: { name: 'DeepMind', url: 'https://github.com/google-deepmind/distrax' } },
    { id: 'rlax', acronym: 'RLax', name: 'RLax', description: 'RL for JAX.', category: 'Operaciones de IA', source: { name: 'DeepMind', url: 'https://github.com/google-deepmind/rlax' } },
    { id: 'ray-train', acronym: 'RayTrain', name: 'Ray Train', description: 'Distributed training.', category: 'Operaciones de IA', source: { name: 'Anyscale', url: 'https://docs.ray.io/en/latest/train/train.html' } }
];
