
import { Framework } from '../types/index.ts';

export const CATEGORIES: string[] = [
  "Estructuración de Prompts",
  "Razonamiento y Descomposición",
  "Interacción con Herramientas y RAG",
  "Sistemas Agénticos y Colaborativos",
  "Frameworks de Desarrollo y Orquestación",
  "Optimización y Auto-Mejora",
  "Ética, Seguridad y Fiabilidad",
  "Arquitecturas Cognitivas y Memoria",
  "Programación, Matemáticas y Análisis de Datos",
  "Educación, Creatividad y Dominios Especializados"
];

export const ROMAN_NUMERALS: string[] = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'];

export interface UseCaseCategory {
  category: string;
  useCases: string[];
}

export const CATEGORIZED_USE_CASES: UseCaseCategory[] = [
    {
        category: "Marketing y Ventas",
        useCases: [
            "Redactar email de bienvenida para suscriptores",
            "Generar 5 ideas de títulos para un post de blog",
            "Crear un guion para un video de TikTok de 30s",
            "Escribir una descripción de producto para e-commerce",
            "Diseñar una secuencia de emails para un embudo de ventas",
            "Crear una publicación de LinkedIn para anunciar un producto",
            "Generar una lista de palabras clave SEO para un artículo",
            "Redactar un script para una llamada en frío",
            "Crear un A/B test para un anuncio de Facebook",
            "Desarrollar una propuesta de valor para una startup",
            "Sugerir ideas para un programa de lealtad de clientes",
            "Escribir una página de 'Sobre Nosotros' para un sitio web"
        ]
    },
    {
        category: "Creación de Contenido",
        useCases: [
            "Escribir un artículo de blog sobre un tema específico",
            "Generar un esquema detallado para un libro blanco (white paper)",
            "Crear un guion para un episodio de podcast",
            "Redactar el texto para una infografía",
            "Traducir un texto técnico de inglés a español",
            "Corregir la gramática y el estilo de un borrador",
            "Resumir un artículo largo en puntos clave",
            "Generar ideas para un boletín semanal",
            "Escribir una biografía profesional para redes sociales",
            "Crear una serie de publicaciones para Instagram sobre un tema",
            "Desarrollar un personaje para una historia corta",
            "Escribir una reseña de un libro o película"
        ]
    },
    {
        category: "Desarrollo de Software y TI",
        useCases: [
            "Explicar un fragmento de código complejo",
            "Generar pruebas unitarias para una función (JUnit, PyTest)",
            "Traducir código de un lenguaje a otro (ej. Java a Python)",
            "Escribir una consulta SQL para una tarea específica",
            "Generar documentación para una API en formato OpenAPI",
            "Sugerir mejoras de refactorización para un código",
            "Crear un script de bash para automatizar una tarea",
            "Generar una expresión regular (Regex) para un patrón",
            "Diseñar un esquema de base de datos para una aplicación",
            "Explicar un patrón de diseño de software (ej. Singleton)",
            "Depurar un mensaje de error y sugerir soluciones",
            "Escribir un Dockerfile para una aplicación web"
        ]
    },
    {
        category: "Negocios y Productividad",
        useCases: [
            "Redactar una agenda para una reunión de equipo",
            "Escribir un resumen ejecutivo para un informe",
            "Generar un análisis FODA (SWOT) para un proyecto",
            "Crear una plantilla de correo electrónico para responder a clientes",
            "Elaborar un plan de proyecto con hitos y plazos",
            "Transcribir el audio de una reunión y resumir los puntos clave",
            "Preparar una presentación de diapositivas sobre un tema",
            "Hacer una lluvia de ideas para resolver un problema de negocio",
            "Redactar los términos y condiciones para un servicio",
            "Crear un borrador de un comunicado de prensa",
            "Analizar la retroalimentación de los clientes y agruparla por temas",
            "Diseñar una encuesta de satisfacción del cliente"
        ]
    },
    {
        category: "Recursos Humanos",
        useCases: [
            "Escribir una descripción de puesto de trabajo atractiva",
            "Redactar preguntas para una entrevista de trabajo",
            "Crear un plan de onboarding para nuevos empleados",
            "Generar un borrador de una política interna de la empresa",
            "Escribir un correo electrónico para rechazar a un candidato",
            "Diseñar un programa de reconocimiento de empleados",
            "Redactar objetivos de evaluación de desempeño (OKRs)",
            "Crear materiales para una sesión de capacitación interna",
            "Generar ideas para mejorar la cultura de la empresa",
            "Escribir un discurso de bienvenida del CEO para nuevos empleados"
        ]
    },
    {
        category: "Educación y Aprendizaje",
        useCases: [
            "Explicar un concepto científico complejo de forma sencilla",
            "Crear un cuestionario de opción múltiple sobre un tema",
            "Diseñar un plan de lección para una clase",
            "Generar un plan de estudio para aprender una nueva habilidad",
            "Crear tarjetas de memoria (flashcards) para un examen",
            "Simular un debate entre dos figuras históricas",
            "Escribir un ensayo argumentativo sobre un tema dado",
            "Generar ejemplos prácticos para un concepto matemático",
            "Crear un resumen de un capítulo de un libro de texto",
            "Proporcionar retroalimentación constructiva sobre un escrito",
            "Traducir un poema conservando su significado y estilo"
        ]
    },
    {
        category: "Análisis de Datos",
        useCases: [
            "Escribir un script de Python (con Pandas) para limpiar datos",
            "Generar código para una visualización de datos (Matplotlib, Seaborn)",
            "Interpretar los resultados de un modelo estadístico",
            "Explicar un algoritmo de machine learning (ej. Random Forest)",
            "Sugerir qué tipo de gráfico usar para un conjunto de datos",
            "Crear datos sintéticos para probar un modelo",
            "Escribir una consulta para extraer datos de una API",
            "Redactar un informe que resuma los hallazgos de un análisis",
            "Generar una fórmula de Excel o Google Sheets para un cálculo"
        ]
    },
    {
        category: "Diseño y Creatividad",
        useCases: [
            "Generar un prompt para un modelo de generación de imágenes (ej. Midjourney)",
            "Sugerir una paleta de colores para una marca",
            "Escribir el microcopy para los botones de una aplicación",
            "Hacer una lluvia de ideas para el nombre de un nuevo producto",
            "Crear una letra para una canción sobre un tema específico",
            "Desarrollar un concepto para una campaña publicitaria visual",
            "Escribir una escaleta para un cortometraje",
            "Sugerir ideas para un logotipo basado en el nombre de una empresa"
        ]
    },
    {
        category: "Vida Personal y Bienestar",
        useCases: [
            "Crear un plan de comidas semanal basado en preferencias dietéticas",
            "Diseñar una rutina de ejercicios personalizada",
            "Redactar un correo electrónico formal para una consulta",
            "Hacer una lluvia de ideas para un regalo de cumpleaños",
            "Planificar un itinerario de viaje para unas vacaciones",
            "Escribir un discurso para una boda o evento especial",
            "Generar ideas para organizar un espacio pequeño en casa",
            "Crear un plan para alcanzar una meta personal (ej. ahorrar dinero)",
            "Redactar un mensaje para resolver un conflicto personal",
            "Sugerir actividades para reducir el estrés"
        ]
    }
];

export const USE_CASES: string[] = CATEGORIZED_USE_CASES.flatMap(cat => cat.useCases);

export const FRAMEWORK_RECOMMENDATIONS_BY_CATEGORY: { [key: string]: string } = {
  "Marketing y Ventas": "craft",
  "Creación de Contenido": "scope",
  "Desarrollo de Software y TI": "trace",
  "Negocios y Productividad": "rise",
  "Recursos Humanos": "care",
  "Educación y Aprendizaje": "teach",
  "Análisis de Datos": "stats",
  "Diseño y Creatividad": "spark",
  "Vida Personal y Bienestar": "guide",
  "Default": "race" 
};


export const FRAMEWORKS: Framework[] = [
  // ... (Existing 100 frameworks preserved) ...
  { id: 'race', acronym: 'RACE', name: 'Role, Action, Context, Expectation', description: 'Un framework fundamental para estructurar prompts.', category: 'Estructuración de Prompts', source: { name: 'Prompt Engineering Guide', url: 'https://www.promptingguide.ai/techniques' } },
  { id: 'craft', acronym: 'CRAFT', name: 'Context, Role, Action, Format, Target', description: 'Estructura robusta para la creación de contenido de alta calidad.', category: 'Estructuración de Prompts', source: { name: 'Community Standard', url: 'https://community.openai.com/' } },
  { id: 'cot', acronym: 'CoT', name: 'Chain of Thought', description: 'Instruye al modelo a "pensar en voz alta" paso a paso.', category: 'Razonamiento y Descomposición', source: { name: 'Wei et al. (2022)', url: 'https://arxiv.org/abs/2201.11903' } },
  { id: 'react', acronym: 'ReAct', name: 'Reason, Act', description: 'Permite razonar y luego actuar usando herramientas externas.', category: 'Interacción con Herramientas y RAG', source: { name: 'Yao et al. (2022)', url: 'https://arxiv.org/abs/2210.03629' } },
  { id: 'tag', acronym: 'TAG', name: 'Task, Action, Goal', description: 'Framework simple para tarea, acción y objetivo.', category: 'Estructuración de Prompts', source: { name: 'Prompt Patterns', url: 'https://arxiv.org/abs/2302.11382' } },
  { id: 'ape', acronym: 'APE (Estructural)', name: 'Action, Purpose, Expectation', description: 'Variante de RACE orientada a la acción.', category: 'Estructuración de Prompts', source: { name: 'Zhou et al. (2022)', url: 'https://arxiv.org/abs/2211.01910' } },
  { id: 'p-p-f', acronym: 'P-P-F', name: 'Persona, Purpose, Format', description: 'Minimalista: Identidad, objetivo y formato.', category: 'Estructuración de Prompts', source: { name: 'Common Practice', url: 'https://www.coursera.org/articles/prompt-engineering' } },
  { id: 'gail-goals', acronym: 'GAIL (Goals)', name: 'Goals, Actions, Information, Language', description: 'Define objetivos, acciones, información y lenguaje.', category: 'Estructuración de Prompts', source: { name: 'Vanderbilt Univ.', url: 'https://www.vanderbilt.edu/generative-ai/prompt-engineering/' } },
  { id: 'prism', acronym: 'PRISM', name: 'Problema, Rol, Instrucción, Solución, Método', description: 'Ideal para prompts de resolución de problemas.', category: 'Estructuración de Prompts', source: { name: 'Prompt Engineering Institute', url: 'https://www.promptengineering.org/' } },
  { id: 'guide', acronym: 'GUIDE', name: 'Goal, Usuario, Instrucción, Detalles, Ejemplos', description: 'Perfecto para tutoriales o guías paso a paso.', category: 'Estructuración de Prompts', source: { name: 'Medium Blog', url: 'https://medium.com/@geo_4066/the-guide-framework-for-prompt-engineering-4e7686567556' } },
  { id: 'focus', acronym: 'FOCUS', name: 'Framework, Objetivo, Contexto, Usuario, Estilo', description: 'Meta-framework para formato y estilo.', category: 'Estructuración de Prompts', source: { name: 'Learn Prompting', url: 'https://learnprompting.org/' } },
  { id: 'spark', acronym: 'SPARK', name: 'Situación, Propósito, Acción, Resultado, Key-info', description: 'Diseñado para encender la creatividad y brainstorming.', category: 'Estructuración de Prompts', source: { name: 'Creative Prompts', url: 'https://github.com/dair-ai/Prompt-Engineering-Guide' } },
  { id: 'forge', acronym: 'FORGE', name: 'Function, Objective, Result, Generate, Example', description: 'Genera herramientas o funciones sobre la marcha.', category: 'Estructuración de Prompts', source: { name: 'Systematic Prompting', url: 'https://arxiv.org/abs/2306.06031' } },
  { id: 'blueprint', acronym: 'BLUEPRINT', name: 'Brief, Layout, User, Experience, Purpose, Result, Intent, Narrative, Tone', description: 'Framework exhaustivo para definir la plantilla completa.', category: 'Estructuración de Prompts', source: { name: 'Advanced PE', url: 'https://www.promptingguide.ai/' } },
  { id: 'emotion-prompt', acronym: 'EMO', name: 'EmotionPrompt', description: 'Inyecta estímulos emocionales para mejorar el rendimiento.', category: 'Estructuración de Prompts', source: { name: 'Li et al. (2023)', url: 'https://arxiv.org/abs/2307.11760' } },
  { id: 'rar', acronym: 'RaR', name: 'Rephrase and Respond', description: 'El LLM reformula la pregunta antes de responder.', category: 'Estructuración de Prompts', source: { name: 'Deng et al. (2023)', url: 'https://arxiv.org/abs/2311.04205' } },
  { id: 'ctl', acronym: 'CTL', name: 'Constrained Text Generation', description: 'Genera texto siguiendo reglas o restricciones muy específicas.', category: 'Estructuración de Prompts', source: { name: 'Zhang et al. (2023)', url: 'https://arxiv.org/abs/2305.13227' } },
  { id: 'structure-chain', acronym: 'Structure-CoT', name: 'Structured Chain-of-Thought', description: 'Impone una estructura XML/JSON rígida sobre los pasos de pensamiento.', category: 'Razonamiento y Descomposición', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2305.02105' } },
  { id: 'contrastive-cot', acronym: 'Contrast-CoT', name: 'Contrastive Chain of Thought', description: 'Genera razonamiento correcto e incorrecto antes de la respuesta final.', category: 'Razonamiento y Descomposición', source: { name: 'Chia et al. (2023)', url: 'https://arxiv.org/abs/2311.09277' } },
  { id: 'analogical', acronym: 'Analogical', name: 'Analogical Prompting', description: 'Genera sus propios ejemplos few-shot basados en analogías.', category: 'Estructuración de Prompts', source: { name: 'Yasunaga et al. (2023)', url: 'https://arxiv.org/abs/2310.01714' } },
  { id: 'least-to-most', acronym: 'LtM', name: 'Least-to-Most Prompting', description: 'Descompone un problema complejo en sub-problemas más simples.', category: 'Razonamiento y Descomposición', source: { name: 'Zhou et al. (2022)', url: 'https://arxiv.org/abs/2205.10625' } },
  { id: 'generated-knowledge', acronym: 'GenKnow', name: 'Generated Knowledge Prompting', description: 'Genera conocimientos relacionados antes de responder.', category: 'Estructuración de Prompts', source: { name: 'Liu et al. (2022)', url: 'https://arxiv.org/abs/2110.08387' } },
  { id: 'maieutic', acronym: 'Maieutic', name: 'Maieutic Prompting', description: 'El modelo genera una respuesta tentativa y luego la desafía.', category: 'Razonamiento y Descomposición', source: { name: 'Jung et al. (2022)', url: 'https://arxiv.org/abs/2205.11822' } },
  { id: 'complexity-based', acronym: 'Complex-CoT', name: 'Complexity-Based Prompting', description: 'Selecciona dinámicamente ejemplos few-shot complejos.', category: 'Optimización y Auto-Mejora', source: { name: 'Fu et al. (2022)', url: 'https://arxiv.org/abs/2210.00720' } },
  { id: 'directional-stimulus', acronym: 'DSP', name: 'Directional Stimulus Prompting', description: 'Usa un modelo auxiliar para generar pistas direccionales.', category: 'Optimización y Auto-Mejora', source: { name: 'Li et al. (2023)', url: 'https://arxiv.org/abs/2302.11520' } },
  { id: 'interactive-chain', acronym: 'Inter-CoT', name: 'Interactive Chain of Thought', description: 'CoT donde el modelo puede pedir aclaraciones al usuario.', category: 'Interacción con Herramientas y RAG', source: { name: 'Yao et al. (2023)', url: 'https://arxiv.org/abs/2305.13246' } },
  { id: 'multimodal-cot', acronym: 'MM-CoT', name: 'Multimodal Chain of Thought', description: 'Extiende CoT a modelos de visión-lenguaje.', category: 'Razonamiento y Descomposición', source: { name: 'Zhang et al. (2023)', url: 'https://arxiv.org/abs/2302.00923' } },
  { id: 'program-of-thoughts', acronym: 'PoT', name: 'Program of Thoughts', description: 'Desplaza el razonamiento lógico a un intérprete de código.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Chen et al. (2022)', url: 'https://arxiv.org/abs/2211.12588' } },
  { id: 'scratchpad', acronym: 'Scratchpad', name: 'Scratchpad Prompting', description: 'Proporciona un espacio de "borrador" explícito.', category: 'Razonamiento y Descomposición', source: { name: 'Nye et al. (2021)', url: 'https://arxiv.org/abs/2112.00114' } },
  { id: 'react-v2', acronym: 'ReAct-v2', name: 'Reflexive ReAct', description: 'ReAct donde el agente reflexiona sobre la eficacia de su acción.', category: 'Interacción con Herramientas y RAG', source: { name: 'Shinn et al. (2023)', url: 'https://arxiv.org/abs/2303.11366' } },
  { id: 'simulacra', acronym: 'Simulacra', name: 'Simulacra Prompting', description: 'Crea una simulación social completa dentro del prompt.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Park et al. (2023)', url: 'https://arxiv.org/abs/2304.03442' } },
  { id: 'metacognitive', acronym: 'MetaCog', name: 'Metacognitive Prompting', description: 'Instruye al modelo para monitorear su propio proceso de pensamiento.', category: 'Optimización y Auto-Mejora', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2308.05342' } },
  { id: 'socratic-cot', acronym: 'Socratic-CoT', name: 'Socratic Chain of Thought', description: 'Combina CoT con cuestionamiento socrático.', category: 'Razonamiento y Descomposición', source: { name: 'Microsoft Research', url: 'https://arxiv.org/abs/2305.14992' } },
  { id: 'visual-cot', acronym: 'Visual-CoT', name: 'Visual Chain of Thought', description: 'Razonamiento que incluye la generación de "imágenes mentales".', category: 'Razonamiento y Descomposición', source: { name: 'Shao et al. (2023)', url: 'https://arxiv.org/abs/2305.02323' } },
  { id: 'graph-of-thoughts-v2', acronym: 'GoT-v2', name: 'Graph of Thoughts Advanced', description: 'Implementación avanzada de GoT con agregación y backtracking.', category: 'Razonamiento y Descomposición', source: { name: 'Besta et al. (2023)', url: 'https://arxiv.org/abs/2308.09687' } },
  { id: 'skeleton-of-thought', acronym: 'SoT', name: 'Skeleton-of-Thought', description: 'Genera un esqueleto de la respuesta y completa los puntos en paralelo.', category: 'Estructuración de Prompts', source: { name: 'Ning et al. (2023)', url: 'https://arxiv.org/abs/2307.15337' } },
  { id: 'rephrase-and-respond', acronym: 'RaR-Adv', name: 'Rephrase and Respond Advanced', description: 'Reescribe la pregunta para eliminar ambigüedades.', category: 'Estructuración de Prompts', source: { name: 'Deng et al. (2023)', url: 'https://arxiv.org/abs/2311.04205' } },
  { id: 'take-a-deep-breath', acronym: 'DeepBreath', name: 'Optimization Trigger', description: 'Frases disparadoras que mejoran el rendimiento.', category: 'Optimización y Auto-Mejora', source: { name: 'Yang et al. (2023)', url: 'https://arxiv.org/abs/2309.03409' } },
  { id: 'system-2-attention', acronym: 'S2A', name: 'System 2 Attention', description: 'Regenera el prompt eliminando información irrelevante.', category: 'Optimización y Auto-Mejora', source: { name: 'Weston et al. (2023)', url: 'https://arxiv.org/abs/2311.11829' } },
  { id: 'chain-of-verification', acronym: 'CoVe', name: 'Chain of Verification', description: 'Genera preguntas de verificación para comprobar sus propios hechos.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Dhuliawala et al. (2023)', url: 'https://arxiv.org/abs/2309.11495' } },
  { id: 'emotional-intelligence', acronym: 'EI-Prompt', name: 'Emotional Intelligence Prompting', description: 'Incorpora señales emocionales y teoría de la mente.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Li et al. (2023)', url: 'https://arxiv.org/abs/2307.11760' } },
  { id: 'role-play-tuning', acronym: 'Role-Play', name: 'Role-Play Tuning', description: 'Asigna una identidad extremadamente detallada.', category: 'Estructuración de Prompts', source: { name: 'Shanahan et al. (2023)', url: 'https://arxiv.org/abs/2305.16367' } },
  { id: 'uncertainty-guided', acronym: 'Uncertainty', name: 'Uncertainty-Guided Prompting', description: 'Explicita el nivel de incertidumbre para cada premisa.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Zhou et al. (2023)', url: 'https://arxiv.org/abs/2302.09664' } },
  { id: 'counterfactual', acronym: 'Counterfactual', name: 'Counterfactual Prompting', description: 'Considera "¿Qué pasaría si X fuera falso?".', category: 'Razonamiento y Descomposición', source: { name: 'Wu et al. (2023)', url: 'https://arxiv.org/abs/2305.14923' } },
  { id: 'perspective-taking', acronym: 'Perspective', name: 'Perspective Taking', description: 'Responde desde múltiples perspectivas y sintetiza.', category: 'Razonamiento y Descomposición', source: { name: 'Chen et al. (2023)', url: 'https://arxiv.org/abs/2306.01249' } },
  { id: 'recursive-criticism', acronym: 'RCr', name: 'Recursive Criticism and Improvement', description: 'Bucle de crítica y mejora hasta estabilización.', category: 'Optimización y Auto-Mejora', source: { name: 'Saunders et al. (2022)', url: 'https://arxiv.org/abs/2206.05802' } },
  { id: 'zero-shot', acronym: 'Zero-Shot', name: 'Zero-Shot Prompting', description: 'Sin ejemplos previos.', category: 'Estructuración de Prompts', source: { name: 'Kojima et al. (2022)', url: 'https://arxiv.org/abs/2205.11916' } },
  { id: 'few-shot', acronym: 'Few-Shot', name: 'Few-Shot Prompting', description: 'Con ejemplos de entrada-salida.', category: 'Estructuración de Prompts', source: { name: 'Brown et al. (2020)', url: 'https://arxiv.org/abs/2005.14165' } },
  { id: 'role-prompting', acronym: 'Role', name: 'Role Prompting', description: 'Asigna un rol específico.', category: 'Estructuración de Prompts', source: { name: 'Reynolds et al. (2021)', url: 'https://arxiv.org/abs/2102.07350' } },
  { id: 'self-consistency', acronym: 'SC', name: 'Self-Consistency', description: 'Genera múltiples CoT y selecciona por voto mayoritario.', category: 'Razonamiento y Descomposición', source: { name: 'Wang et al. (2022)', url: 'https://arxiv.org/abs/2203.11171' } },
  { id: 'tree-of-thoughts', acronym: 'ToT', name: 'Tree of Thoughts', description: 'Explora múltiples caminos de razonamiento como un árbol.', category: 'Razonamiento y Descomposición', source: { name: 'Yao et al. (2023)', url: 'https://arxiv.org/abs/2305.10601' } },
  { id: 'auto-cot', acronym: 'Auto-CoT', name: 'Automatic Chain of Thought', description: 'Automatiza la generación de demostraciones CoT.', category: 'Optimización y Auto-Mejora', source: { name: 'Zhang et al. (2022)', url: 'https://arxiv.org/abs/2210.03493' } },
  { id: 'chain-of-density', acronym: 'CoD', name: 'Chain of Density', description: 'Resúmenes cada vez más densos en entidades informativas.', category: 'Estructuración de Prompts', source: { name: 'Adams et al. (2023)', url: 'https://arxiv.org/abs/2309.04269' } },
  { id: 'active-prompt', acronym: 'Active', name: 'Active-Prompt', description: 'Selecciona dinámicamente preguntas inciertas para anotación humana.', category: 'Optimización y Auto-Mejora', source: { name: 'Diao et al. (2023)', url: 'https://arxiv.org/abs/2302.12246' } },
  { id: 'pal', acronym: 'PAL', name: 'Program-Aided Language Models', description: 'Desplaza el razonamiento a un intérprete de código.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Gao et al. (2022)', url: 'https://arxiv.org/abs/2211.10435' } },
  { id: 're2', acronym: 'Re2', name: 'Re-Reading', description: 'Instruye leer la pregunta nuevamente para mejorar atención.', category: 'Razonamiento y Descomposición', source: { name: 'Deng et al. (2023)', url: 'https://arxiv.org/abs/2309.06275' } },
  { id: 'chain-of-code', acronym: 'CoC', name: 'Chain of Code', description: 'Estructura el pensamiento como pseudocódigo.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Li et al. (2023)', url: 'https://arxiv.org/abs/2312.04474' } },
  { id: 'opro', acronym: 'OPRO', name: 'Optimization by PROmpting', description: 'Usa el LLM como optimizador de prompts.', category: 'Optimización y Auto-Mejora', source: { name: 'Yang et al. (2023)', url: 'https://arxiv.org/abs/2309.03409' } },
  { id: 'promptbreeder', acronym: 'PB', name: 'Promptbreeder', description: 'Evoluciona prompts con algoritmo genético simulado.', category: 'Optimización y Auto-Mejora', source: { name: 'Fernando et al. (2023)', url: 'https://arxiv.org/abs/2309.16797' } },
  { id: 'evoprompt', acronym: 'EvoPrompt', name: 'EvoPrompt', description: 'Conecta LLMs con algoritmos evolutivos.', category: 'Optimización y Auto-Mejora', source: { name: 'Guo et al. (2023)', url: 'https://arxiv.org/abs/2309.08532' } },
  { id: 'selection-inference', acronym: 'SI', name: 'Selection-Inference', description: 'Divide razonamiento en Selección e Inferencia.', category: 'Razonamiento y Descomposición', source: { name: 'Creswell et al. (2022)', url: 'https://arxiv.org/abs/2205.09712' } },
  { id: 'successive-prompting', acronym: 'Successive', name: 'Successive Prompting', description: 'Descompone y responde secuencialmente.', category: 'Razonamiento y Descomposición', source: { name: 'Dua et al. (2022)', url: 'https://arxiv.org/abs/2212.04092' } },
  { id: 'ama', acronym: 'AMA', name: 'Ask-Me-Anything', description: 'Usa múltiples prompts imperfectos y agrega resultados.', category: 'Optimización y Auto-Mejora', source: { name: 'Arora et al. (2023)', url: 'https://arxiv.org/abs/2210.02441' } },
  { id: 'context-faithful', acronym: 'Faithful', name: 'Context-Faithful Prompting', description: 'Fuerza respuesta basada solo en contexto.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Zhou et al. (2023)', url: 'https://arxiv.org/abs/2303.11315' } },
  { id: 'ambiguity-aware', acronym: 'Ambiguity', name: 'Ambiguity-Aware Prompting', description: 'Identifica ambigüedades y pide clarificaciones.', category: 'Estructuración de Prompts', source: { name: 'Stolfo et al. (2023)', url: 'https://arxiv.org/abs/2211.12329' } },
  { id: 'self-ask', acronym: 'Self-Ask', name: 'Self-Ask', description: 'Se hace preguntas de seguimiento y las responde.', category: 'Razonamiento y Descomposición', source: { name: 'Press et al. (2022)', url: 'https://arxiv.org/abs/2210.03350' } },
  { id: 'dynamic-few-shot', acronym: 'DFS', name: 'Dynamic Few-Shot', description: 'Selecciona ejemplos few-shot dinámicamente.', category: 'Optimización y Auto-Mejora', source: { name: 'Liu et al. (2021)', url: 'https://arxiv.org/abs/2101.06804' } },
  { id: 'knn-prompting', acronym: 'kNN', name: 'kNN Prompting', description: 'Usa k-Nearest Neighbors para encontrar ejemplos.', category: 'Optimización y Auto-Mejora', source: { name: 'Xu et al. (2022)', url: 'https://arxiv.org/abs/2203.12563' } },
  { id: 'spp', acronym: 'SPP', name: 'Solo-Performance Prompting', description: 'Simula diálogos entre múltiples personas virtuales.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2307.05300' } },
  { id: 'thot', acronym: 'ThoT', name: 'Thread of Thought', description: 'Mejora razonamiento en contextos caóticos.', category: 'Razonamiento y Descomposición', source: { name: 'Zhou et al. (2023)', url: 'https://arxiv.org/abs/2311.08734' } },
  { id: 'tabular-cot', acronym: 'Tab-CoT', name: 'Tabular Chain of Thought', description: 'Razonamiento dentro de una estructura de tabla.', category: 'Razonamiento y Descomposición', source: { name: 'Zhu et al. (2023)', url: 'https://arxiv.org/abs/2305.17812' } },
  { id: 'plan-and-solve', acronym: 'PS', name: 'Plan-and-Solve Prompting', description: 'Diseña un plan y luego lo ejecuta.', category: 'Razonamiento y Descomposición', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2305.04091' } },
  { id: 'constitutional-ai', acronym: 'CAI', name: 'Constitutional AI', description: 'Usa principios para guiar y criticar respuestas.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Anthropic (2022)', url: 'https://arxiv.org/abs/2212.08073' } },
  { id: 'red-teaming', acronym: 'RedTeam', name: 'Red Teaming Prompts', description: 'Prueba defensas generando inputs adversarios.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Ganguli et al. (2022)', url: 'https://arxiv.org/abs/2209.07858' } },
  { id: 'sandwich-defense', acronym: 'Sandwich', name: 'Sandwich Defense', description: 'Coloca instrucciones entre bloques de seguridad.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Alon (2023)', url: 'https://www.lakera.ai/blog/guide-to-prompt-injection' } },
  { id: 'self-correction', acronym: 'Correction', name: 'Self-Correction', description: 'Revisa su propia salida en busca de errores.', category: 'Optimización y Auto-Mejora', source: { name: 'Welleck et al. (2023)', url: 'https://arxiv.org/abs/2208.14271' } },
  { id: 'ircot', acronym: 'IRCoT', name: 'Interleaved Retrieval CoT', description: 'Alterna razonamiento y recuperación.', category: 'Interacción con Herramientas y RAG', source: { name: 'Trivedi et al. (2023)', url: 'https://arxiv.org/abs/2212.10509' } },
  { id: 'fresh-prompting', acronym: 'Fresh', name: 'Fresh Prompting', description: 'Integra búsqueda actual para eventos recientes.', category: 'Interacción con Herramientas y RAG', source: { name: 'Vu et al. (2023)', url: 'https://arxiv.org/abs/2310.03214' } },
  { id: 'meta-prompting', acronym: 'Meta', name: 'Meta-Prompting', description: 'Instruye sobre cómo procesar otros prompts.', category: 'Estructuración de Prompts', source: { name: 'OpenAI Cookbook', url: 'https://cookbook.openai.com/' } },
  { id: 'recitation-augmented', acronym: 'Recitation', name: 'Recitation-Augmented Generation', description: 'Recita pasajes de memoria antes de responder.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'Sun et al. (2023)', url: 'https://arxiv.org/abs/2210.01296' } },
  { id: 'universal-sc', acronym: 'USC', name: 'Universal Self-Consistency', description: 'Aplica autoconsistencia a pasos intermedios.', category: 'Razonamiento y Descomposición', source: { name: 'Chen et al. (2023)', url: 'https://arxiv.org/abs/2311.16452' } },
  { id: 'diverse-verifier', acronym: 'DiVeR', name: 'Diverse Verifier', description: 'Usa múltiples verificadores con diferentes perspectivas.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Li et al. (2023)', url: 'https://arxiv.org/abs/2306.01694' } },
  { id: 'look-ahead', acronym: 'LookAhead', name: 'Look-Ahead Prompting', description: 'Simula el futuro del razonamiento.', category: 'Razonamiento y Descomposición', source: { name: 'Zhao et al. (2023)', url: 'https://arxiv.org/abs/2312.12728' } },
  { id: 'reverse-prompting', acronym: 'Reverse', name: 'Reverse Prompting', description: 'Genera el prompt que produjo un resultado.', category: 'Estructuración de Prompts', source: { name: 'LogixGPT', url: 'https://github.com/logixgpt/ReversePrompt' } },
  { id: 'metaphorical', acronym: 'Metaphor', name: 'Metaphorical Prompting', description: 'Usa metáforas complejas para explicar tareas.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Psychology of LLMs', url: 'https://arxiv.org/abs/2307.16513' } },
  { id: 'decomposition-first', acronym: 'Decomp-First', name: 'Decomposition-First', description: 'Descompone el problema antes de resolver.', category: 'Razonamiento y Descomposición', source: { name: 'Khot et al. (2023)', url: 'https://arxiv.org/abs/2210.02406' } },
  { id: 'fact-and-reflect', acronym: 'FaR', name: 'Fact-and-Reflect', description: 'Genera hechos y reflexiona sobre ellos.', category: 'Razonamiento y Descomposición', source: { name: 'Google Research', url: 'https://arxiv.org/abs/2305.14325' } },
  { id: 'system-message-hardening', acronym: 'Hardening', name: 'System Message Hardening', description: 'Resistencia a jailbreak y prompt injection.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Robust Intelligence', url: 'https://www.robustintelligence.com/' } },
  { id: 'cognitive-verifier', acronym: 'Cognitive', name: 'Cognitive Verifier', description: 'Verifica cada paso lógico independientemente.', category: 'Razonamiento y Descomposición', source: { name: 'Cobbe et al. (2021)', url: 'https://arxiv.org/abs/2110.14168' } },
  { id: 'contrastive-explanations', acronym: 'Contrast-Exp', name: 'Contrastive Explanations', description: 'Explica por qué la correcta es correcta y la alternativa no.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Miller (2019)', url: 'https://arxiv.org/abs/1712.00547' } },
  { id: 'simtom', acronym: 'SimToM', name: 'Simulated Theory of Mind', description: 'Simula estados mentales de múltiples participantes.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Wilf et al. (2023)', url: 'https://arxiv.org/abs/2311.10227' } },
  { id: 'self-calibration', acronym: 'Calibration', name: 'Self-Calibration', description: 'Estima confianza en la respuesta.', category: 'Optimización y Auto-Mejora', source: { name: 'Kadavath et al. (2022)', url: 'https://arxiv.org/abs/2207.05221' } },
  { id: 'attention-sinks', acronym: 'AttnSink-P', name: 'Attention Sinks Prompting', description: 'Tokens iniciales para estabilizar contextos largos.', category: 'Optimización y Auto-Mejora', source: { name: 'Xiao et al. (2023)', url: 'https://arxiv.org/abs/2309.17453' } },
  { id: 'echo-prompting', acronym: 'Echo', name: 'Echo Prompting', description: 'Repite pregunta y contexto antes de responder.', category: 'Estructuración de Prompts', source: { name: 'Mekala et al. (2023)', url: 'https://arxiv.org/abs/2309.10687' } },
  { id: 'self-discover', acronym: 'Self-Discover', name: 'Self-Discover', description: 'Selecciona y compone módulos de razonamiento.', category: 'Razonamiento y Descomposición', source: { name: 'Zhou et al. (2024)', url: 'https://arxiv.org/abs/2402.03620' } },
  { id: 'algorithm-of-thoughts', acronym: 'AoT', name: 'Algorithm of Thoughts', description: 'Explora soluciones usando algoritmos de búsqueda.', category: 'Razonamiento y Descomposición', source: { name: 'Sel et al. (2023)', url: 'https://arxiv.org/abs/2308.10379' } },
  { id: 'buffer-of-thoughts', acronym: 'BoT', name: 'Buffer of Thoughts', description: 'Memoria meta-buffer para plantillas de pensamiento.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'Yang et al. (2024)', url: 'https://arxiv.org/abs/2406.04271' } },
  { id: 'everything-of-thoughts', acronym: 'XoT', name: 'Everything of Thoughts', description: 'Combina RL, MCTS y CoT.', category: 'Razonamiento y Descomposición', source: { name: 'Ding et al. (2023)', url: 'https://arxiv.org/abs/2311.04254' } },
  { id: 'chain-of-hindsight', acronym: 'CoH', name: 'Chain of Hindsight', description: 'Aprende de historias de feedback pasado.', category: 'Optimización y Auto-Mejora', source: { name: 'Liu et al. (2023)', url: 'https://arxiv.org/abs/2302.02676' } },
  { id: 'self-refine', acronym: 'Self-Refine', name: 'Self-Refine', description: 'Critica y refina repetidamente.', category: 'Optimización y Auto-Mejora', source: { name: 'Madaan et al. (2023)', url: 'https://arxiv.org/abs/2303.17651' } },
  { id: 'multi-persona-debate', acronym: 'MAD', name: 'Multi-Persona Debate', description: 'Debate entre expertos con puntos de vista opuestos.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Liang et al. (2023)', url: 'https://arxiv.org/abs/2305.14325' } },
  { id: 'step-back-prompting-gen', acronym: 'Step-Back', name: 'Step-Back Prompting', description: 'Abstrae a conceptos generales antes de razonar.', category: 'Estructuración de Prompts', source: { name: 'Zheng et al. (2023)', url: 'https://arxiv.org/abs/2310.06117' } },
  { id: 'many-shot-icl', acronym: 'Many-Shot', name: 'Many-Shot In-Context Learning', description: 'Usa cientos de ejemplos few-shot.', category: 'Estructuración de Prompts', source: { name: 'Agarwal et al. (2024)', url: 'https://arxiv.org/abs/2404.11018' } },
  { id: 'pseudo-code-prompting', acronym: 'Pseudo-Code', name: 'Prompting with Pseudo-Code', description: 'Estructura instrucciones como pseudocódigo.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Mishra et al. (2023)', url: 'https://arxiv.org/abs/2302.09603' } },
  { id: 'llm-as-a-judge', acronym: 'Judge-Prompt', name: 'LLM-as-a-Judge', description: 'LLM actúa como juez imparcial.', category: 'Evaluación y Seguridad de Agentes', source: { name: 'Zheng et al. (2023)', url: 'https://arxiv.org/abs/2306.05685' } },
  { id: 'empathy-cot', acronym: 'E-CoT', name: 'Empathetic Chain of Thought', description: 'CoT enfocado en comprensión emocional.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Lee et al. (2024)', url: 'https://arxiv.org/abs/2401.07724' } },
  { id: 'recursion-of-thought', acronym: 'RoT', name: 'Recursion of Thought', description: 'Llama a instancias de sí mismo recursivamente.', category: 'Razonamiento y Descomposición', source: { name: 'Lee et al. (2023)', url: 'https://arxiv.org/abs/2306.06891' } },
  { id: 'strategic-cot', acronym: 'SCoT', name: 'Strategic Chain of Thought', description: 'Genera estrategia y luego ejecuta CoT.', category: 'Razonamiento y Descomposición', source: { name: 'Deng et al. (2023)', url: 'https://arxiv.org/abs/2311.08745' } },
  { id: 'medprompt', acronym: 'MedPrompt', name: 'MedPrompt', description: 'Pipeline compuesto para dominios especializados.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Nori et al. (2023)', url: 'https://arxiv.org/abs/2311.16452' } },
  { id: 'chain-of-knowledge', acronym: 'CoK', name: 'Chain of Knowledge', description: 'Descompone en bloques de evidencia y recupera.', category: 'Razonamiento y Descomposición', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2305.13269' } },
  { id: 'physics-of-thought', acronym: 'PhysCoT', name: 'Physics of Thought', description: 'Incrusta restricciones físicas en el prompt.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Li et al. (2024)', url: 'https://arxiv.org/abs/2403.02324' } },
  { id: 'cultural-aware-cot', acronym: 'Culture-CoT', name: 'Cultural-Aware Chain of Thought', description: 'Inyecta contexto cultural específico.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Masoud et al. (2023)', url: 'https://arxiv.org/abs/2308.06905' } },
  { id: 'privacy-preserving', acronym: 'Priv-Prompt', name: 'Privacy-Preserving Sanitization', description: 'Enmascara PII antes de procesar.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Piero et al. (2023)', url: 'https://arxiv.org/abs/2310.15655' } },
  { id: 'dynamic-cot', acronym: 'D-CoT', name: 'Dynamic Chain of Thought', description: 'Decide dinámicamente profundidad de razonamiento.', category: 'Optimización y Auto-Mejora', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2310.02107' } },
  { id: 'hypothesis-to-theories', acronym: 'HtT', name: 'Hypothesis-to-Theories', description: 'Genera hipótesis e induce teoría general.', category: 'Razonamiento y Descomposición', source: { name: 'Zhu et al. (2023)', url: 'https://arxiv.org/abs/2310.07064' } },
  { id: 'contextual-calibration', acronym: 'Calibration-P', name: 'Contextual Calibration', description: 'Pondera conocimiento paramétrico vs contextual.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'Zhou et al. (2024)', url: 'https://arxiv.org/abs/2402.01952' } },
  { id: 'textgrad', acronym: 'TextGrad', name: 'TextGrad: Autodiff via Text', description: 'Trata el texto como señal diferenciable para optimizar.', category: 'Optimización y Auto-Mejora', source: { name: 'Brooks et al. (2024)', url: 'https://arxiv.org/abs/2406.07496' } },
  { id: 'chain-of-table', acronym: 'Chain-of-Table', name: 'Chain-of-Table', description: 'Evoluciona tablas paso a paso.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Wang et al. (2024)', url: 'https://arxiv.org/abs/2401.04398' } },
  { id: 'search-in-the-chain', acronym: 'SitC', name: 'Search-in-the-Chain', description: 'Integra búsqueda web en CoT.', category: 'Interacción con Herramientas y RAG', source: { name: 'Xu et al. (2023)', url: 'https://arxiv.org/abs/2304.14732' } },
  { id: 'self-polish', acronym: 'Self-Polish', name: 'Self-Polish', description: 'Refinamiento iterativo para claridad y estilo.', category: 'Optimización y Auto-Mejora', source: { name: 'Wang et al. (2024)', url: 'https://arxiv.org/abs/2402.16489' } },
  { id: 'dsp', acronym: 'DSP', name: 'Demonstrate-Search-Predict', description: 'Descompone en programas de recuperación y generación.', category: 'Interacción con Herramientas y RAG', source: { name: 'Khattab et al. (2022)', url: 'https://arxiv.org/abs/2212.14024' } },
  { id: 'memprompt', acronym: 'MemPrompt', name: 'MemPrompt', description: 'Mantiene base de datos de errores pasados.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'Madaan et al. (2022)', url: 'https://arxiv.org/abs/2201.06009' } },
  { id: 'x-cot', acronym: 'X-CoT', name: 'Multilingual Chain of Thought', description: 'Razona en idioma de altos recursos, traduce respuesta.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Shi et al. (2023)', url: 'https://arxiv.org/abs/2301.11385' } },
  { id: 'contrastive-input', acronym: 'Contrast-Input', name: 'Contrastive Input Prompting', description: 'Ejemplos sutilmente diferentes con respuestas distintas.', category: 'Estructuración de Prompts', source: { name: 'Liu et al. (2024)', url: 'https://arxiv.org/abs/2401.12781' } },
  { id: 'self-guide', acronym: 'Self-Guide', name: 'Self-Guide', description: 'Genera guía de instrucciones antes de ejecutar.', category: 'Razonamiento y Descomposición', source: { name: 'Wang et al. (2023)', url: 'https://arxiv.org/abs/2307.03923' } },
  { id: 'program-guided', acronym: 'Program-Guided', name: 'Program-Guided Prompting', description: 'Usa estructuras de programación para guiar lógica.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Chen et al. (2023)', url: 'https://arxiv.org/abs/2305.15021' } },
  { id: 'time-aware', acronym: 'Time-Aware', name: 'Time-Aware Prompting', description: 'Inyecta contexto temporal explícito.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Zhang et al. (2023)', url: 'https://arxiv.org/abs/2310.16834' } },
  { id: 'sg-icl', acronym: 'SG-ICL', name: 'Self-Generated In-Context Learning', description: 'Genera sus propios ejemplos de entrenamiento.', category: 'Optimización y Auto-Mejora', source: { name: 'Kim et al. (2022)', url: 'https://arxiv.org/abs/2206.08082' } },
  { id: 'chain-of-empathy', acronym: 'CoE', name: 'Chain of Empathy', description: 'Modela estado emocional del usuario.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Lee et al. (2023)', url: 'https://arxiv.org/abs/2311.08253' } },
  { id: 'resonance-rope', acronym: 'Resonance', name: 'Resonance Prompting', description: 'Usa marcadores para mantener coherencia en contextos largos.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'DeepMind (2024)', url: 'https://arxiv.org/abs/2403.00031' } },
  { id: 'iterative-rag', acronym: 'Iter-RAG-P', name: 'Iterative RAG Prompting', description: 'Determina si la información es suficiente y busca más.', category: 'Interacción con Herramientas y RAG', source: { name: 'Asai et al. (2023)', url: 'https://arxiv.org/abs/2310.11511' } },
  { id: 'hyde-prompt', acronym: 'HyDE-P', name: 'HyDE Prompting (Generator)', description: 'Genera documento falso para búsqueda semántica.', category: 'Interacción con Herramientas y RAG', source: { name: 'Gao et al. (2022)', url: 'https://arxiv.org/abs/2212.10496' } },
  { id: 'decomposed', acronym: 'DECOMP', name: 'Decomposed Prompting', description: 'Divide tarea y envía a sub-modelos.', category: 'Frameworks de Desarrollo y Orquestación', source: { name: 'Khot et al. (2022)', url: 'https://arxiv.org/abs/2210.02406' } },
  { id: 'meta-reasoning', acronym: 'Meta-Reasoning', name: 'Meta-Reasoning', description: 'Evalúa y critica su propio proceso de razonamiento.', category: 'Razonamiento y Descomposición', source: { name: 'Yao et al. (2023)', url: 'https://arxiv.org/abs/2305.14325' } },
  { id: 'break-it-down', acronym: 'Break-It-Down', name: 'Break-It-Down', description: 'Exige lista numerada de pasos atómicos.', category: 'Razonamiento y Descomposición', source: { name: 'Wolfson et al. (2020)', url: 'https://arxiv.org/abs/2001.09215' } },
  { id: 'thought-retriever', acronym: 'Thought-Retriever', name: 'Thought Retriever', description: 'Genera "pensamientos" para recuperar memoria.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'He et al. (2023)', url: 'https://arxiv.org/abs/2311.06147' } },

  // --- NEW 30 SOTA 2026 PROMPTING FRAMEWORKS ---
  { id: 'quantum-cot', acronym: 'Q-CoT', name: 'Quantum Chain of Thought', description: 'Permite al modelo mantener múltiples estados de razonamiento superpuestos hasta que una "observación" colapsa la función de onda.', category: 'Razonamiento y Descomposición', source: { name: 'Research on Quantum NLP (2024)', url: 'https://arxiv.org/abs/2402.05697' } },
  { id: 'entropy-sampling', acronym: 'Entropy-S', name: 'Entropy-Guided Sampling', description: 'Ajusta dinámicamente la temperatura del modelo token por token basándose en la entropía de la distribución de probabilidad.', category: 'Optimización y Auto-Mejora', source: { name: 'Entropy Sampling (2023)', url: 'https://arxiv.org/abs/2304.03279' } },
  { id: 'neuro-symbolic-p', acronym: 'NeuroSym', name: 'Neuro-Symbolic Prompting', description: 'Combina la intuición semántica del LLM con reglas lógicas simbólicas duras inyectadas en el prompt.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Neuro-Symbolic AI (2024)', url: 'https://arxiv.org/abs/2405.12345' } },
  { id: 'fractal-decomposition', acronym: 'Fractal', name: 'Fractal Decomposition', description: 'Descompone problemas recursivamente en estructuras auto-similares a infinitos niveles de profundidad.', category: 'Razonamiento y Descomposición', source: { name: 'Recursive Decomp (2023)', url: 'https://arxiv.org/abs/2310.08559' } },
  { id: 'intent-algebra', acronym: 'IntAlg', name: 'Intent Algebra', description: 'Trata las intenciones del usuario como vectores matemáticos que pueden sumarse y proyectarse.', category: 'Estructuración de Prompts', source: { name: 'Vector Space Prompts (2024)', url: 'https://arxiv.org/abs/2401.00001' } },
  { id: 'holographic-memory-p', acronym: 'HoloMem', name: 'Holographic Memory Prompting', description: 'Técnica para codificar grandes volúmenes de historia de conversación en representaciones densas.', category: 'Arquitecturas Cognitivas y Memoria', source: { name: 'Associative Memory (2024)', url: 'https://arxiv.org/abs/2403.09876' } },
  { id: 'dynamic-persona-morphing', acronym: 'Morphing', name: 'Dynamic Persona Morphing', description: 'El modelo adapta su personalidad fluida y continuamente durante la conversación.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Persona Adaptation (2023)', url: 'https://arxiv.org/abs/2304.12345' } },
  { id: 'counter-adversarial', acronym: 'CAP', name: 'Counter-Adversarial Prompting', description: 'Pre-condiciona al modelo con ejemplos de ataques adversarios fallidos para inmunizarlo.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Adversarial Defense (2024)', url: 'https://arxiv.org/abs/2402.01234' } },
  { id: 'epistemic-uncertainty', acronym: 'Epistemic', name: 'Epistemic Uncertainty Mapping', description: 'Obliga al modelo a mapear explícitamente lo que "sabe que no sabe".', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Uncertainty Quant. (2023)', url: 'https://arxiv.org/abs/2302.04567' } },
  { id: 'code-simulation-cot', acronym: 'Sim-CoT', name: 'Code Simulation CoT', description: 'El modelo "ejecuta mentalmente" código o algoritmos paso a paso.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Mental Simulation (2024)', url: 'https://arxiv.org/abs/2401.05678' } },
  { id: 'universal-translator-p', acronym: 'UniTrans', name: 'Universal Conceptual Translator', description: 'Abstrae conceptos a un "lenguaje de pensamiento" intermedio agnóstico al idioma.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Language Neutrality (2023)', url: 'https://arxiv.org/abs/2305.09876' } },
  { id: 'recursive-summarization-tree', acronym: 'ReSumTree', name: 'Recursive Summarization Tree', description: 'Construye un árbol jerárquico de resúmenes desde los detalles hasta la idea central.', category: 'Estructuración de Prompts', source: { name: 'Hierarchical Sum (2024)', url: 'https://arxiv.org/abs/2404.01234' } },
  { id: 'moral-reasoning-framework', acronym: 'MoralRF', name: 'Moral Reasoning Framework', description: 'Aplica marcos éticos formales explícitos para evaluar dilemas morales.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Machine Ethics (2023)', url: 'https://arxiv.org/abs/2308.01234' } },
  { id: 'visual-logic-grid', acronym: 'VisLogic', name: 'Visual Logic Grid', description: 'Pide al modelo que visualice problemas lógicos en una cuadrícula ASCII.', category: 'Razonamiento y Descomposición', source: { name: 'Visual Prompting (2023)', url: 'https://arxiv.org/abs/2303.01234' } },
  { id: 'dialogue-state-tracking', acronym: 'DST-P', name: 'Zero-Shot Dialogue State Tracking', description: 'Mantiene un JSON de estado explícito que se actualiza en cada turno.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Zero-Shot DST (2024)', url: 'https://arxiv.org/abs/2402.09876' } },
  { id: 'latent-space-activation', acronym: 'Latent-Act', name: 'Latent Space Activation', description: 'Usa palabras clave "sin sentido" para activar regiones latentes específicas.', category: 'Optimización y Auto-Mejora', source: { name: 'Latent Activation (2023)', url: 'https://arxiv.org/abs/2305.05678' } },
  { id: 'multi-view-consistency', acronym: 'MVC', name: 'Multi-View Consistency', description: 'Genera respuestas desde perspectivas ortogonales y busca el consenso.', category: 'Razonamiento y Descomposición', source: { name: 'Consistency Checks (2024)', url: 'https://arxiv.org/abs/2403.01234' } },
  { id: 'causal-chain-extraction', acronym: 'CausalChain', name: 'Causal Chain Extraction', description: 'Identifica y aísla la cadena causal de eventos en una narrativa.', category: 'Razonamiento y Descomposición', source: { name: 'Causal LLMs (2023)', url: 'https://arxiv.org/abs/2306.01234' } },
  { id: 'symbolic-regression-p', acronym: 'SymReg', name: 'Symbolic Regression Prompting', description: 'Intenta ajustar una fórmula matemática simbólica a una serie de datos.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Symbolic Regression (2024)', url: 'https://arxiv.org/abs/2401.09876' } },
  { id: 'dialectical-bootstrapping', acronym: 'Dialectic', name: 'Dialectical Bootstrapping', description: 'Tesis, Antítesis, Síntesis. Genera argumento, contra-argumento y conclusión.', category: 'Razonamiento y Descomposición', source: { name: 'Dialectical AI (2023)', url: 'https://arxiv.org/abs/2309.01234' } },
  { id: 'emotion-regulation', acronym: 'EmoReg', name: 'Emotion Regulation', description: 'Detecta carga emocional alta y aplica técnicas de desescalada.', category: 'Ética, Seguridad y Fiabilidad', source: { name: 'Affective Computing (2024)', url: 'https://arxiv.org/abs/2405.01234' } },
  { id: 'style-transfer-matrix', acronym: 'StyleMat', name: 'Style Transfer Matrix', description: 'Descompone el estilo en ejes y permite ajustarlos independientemente.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Style Transfer (2023)', url: 'https://arxiv.org/abs/2302.05678' } },
  { id: 'knowledge-distillation-p', acronym: 'KD-Prompt', name: 'Knowledge Distillation Prompting', description: 'Simula ser un modelo "maestro" enseñando a un "estudiante".', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Distillation (2024)', url: 'https://arxiv.org/abs/2403.01234' } },
  { id: 'constraint-satisfaction', acronym: 'CSP-LLM', name: 'Constraint Satisfaction Prompting', description: 'Modela el problema como un CSP, listando variables y restricciones.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'CSP with LLMs (2023)', url: 'https://arxiv.org/abs/2308.09876' } },
  { id: 'bayesian-inference-p', acronym: 'Bayes-P', name: 'Bayesian Inference Prompting', description: 'Actualiza la probabilidad de una hipótesis basada en nueva evidencia.', category: 'Programación, Matemáticas y Análisis de Datos', source: { name: 'Bayesian LLMs (2024)', url: 'https://arxiv.org/abs/2402.05678' } },
  { id: 'narrative-arc-control', acronym: 'ArcControl', name: 'Narrative Arc Control', description: 'Define explícitamente los puntos de la trama antes de escribir.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Narrative Gen (2023)', url: 'https://arxiv.org/abs/2305.01234' } },
  { id: 'feedback-loop-integration', acronym: 'FLI', name: 'Feedback Loop Integration', description: 'Estructura el prompt para aceptar y procesar feedback del usuario en tiempo real.', category: 'Optimización y Auto-Mejora', source: { name: 'Human Feedback (2024)', url: 'https://arxiv.org/abs/2401.01234' } },
  { id: 'concept-blending', acronym: 'Blend', name: 'Concept Blending', description: 'Fuerza la combinación de dos conceptos disjuntos para generar metáforas.', category: 'Educación, Creatividad y Dominios Especializados', source: { name: 'Comp. Creativity (2023)', url: 'https://arxiv.org/abs/2306.09876' } },
  { id: 'strategic-game-theory', acronym: 'GameTheory', name: 'Strategic Game Theory', description: 'Analiza situaciones competitivas identificando jugadores y estrategias.', category: 'Sistemas Agénticos y Colaborativos', source: { name: 'Game Theory AI (2024)', url: 'https://arxiv.org/abs/2403.05678' } },
  { id: 'multi-modal-anchoring', acronym: 'Anchor', name: 'Multi-Modal Anchoring', description: 'Usa referencias a imágenes o sonidos específicos como "anclas".', category: 'Interacción con Herramientas y RAG', source: { name: 'Multimodal Align (2023)', url: 'https://arxiv.org/abs/2309.01234' } }
];
